<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLg9a5NI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLg9a5NI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLg9a5NI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLg9a5NI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLg9a5NI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Lg9a5NI',
    'container.build_id' => '4d353ff1',
    'container.build_time' => 1606142361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLg9a5NI');
