<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEtR1VRL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEtR1VRL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEtR1VRL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEtR1VRL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEtR1VRL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EtR1VRL',
    'container.build_id' => 'e02b0f31',
    'container.build_time' => 1606817416,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEtR1VRL');
