<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF081xVy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF081xVy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF081xVy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF081xVy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF081xVy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F081xVy',
    'container.build_id' => 'e17f1aba',
    'container.build_time' => 1605772766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF081xVy');
